### PR TITLE
Updated to support Java 10 and Windows

### PR DESCRIPTION
**Pull request by rcjim**

### CODE REVIEW

**Comment by isuftin** [comment]
@rcjim Just a note, but when trying to run this in test kitchen on MacOS, I got the following error...

```
$ kitchen list

>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: WinRM Transport requires the vagrant-winrm Vagrant plugin to properly communicate with this Vagrant VM. Please install this plugin with: `vagrant plugin install vagrant-winrm' and try again.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

That isn't a big deal but it does create an extra step that wasn't there before as a requirement to run test kitchen. I wonder if that should be placed into the README.md

**Comment by isuftin** [comment]
@rcjim For windows, which of these boxes are you using? 

https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=windows-2012r2

In Test Kitchen, when trying to run `ruby-win-windows-2012r2` I get:

```
$ kitchen converge ruby-win-windows-2012r2
-----> Starting Kitchen (v1.22.0)
-----> Creating <ruby-win-windows-2012r2>...
       Bringing machine 'default' up with 'virtualbox' provider...
       ==> default: Box 'windows-2012r2' could not be found. Attempting to find and install...
           default: Box Provider: virtualbox
           default: Box Version: >= 0
       ==> default: Box file was not detected as metadata. Adding it directly...
       ==> default: Adding box 'windows-2012r2' (v0) for provider: virtualbox
           default: Downloading: windows-2012r2
An error occurred while downloading the remote file. The error
       message, if any, is reproduced below. Please fix this error and try
       again.

       Couldn't open file /Users/isuftin/Chef/cookbooks/cookbook-doi-ssl-filtering/.kitchen/kitchen-vagrant/ruby-win-windows-2012r2/windows-2012r2
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #create action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant up --no-provision --provider virtualbox ----
STDOUT: Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'windows-2012r2' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'windows-2012r2' (v0) for provider: virtualbox
    default: Downloading: windows-2012r2

STDERR: An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Users/isuftin/Chef/cookbooks/cookbook-doi-ssl-filtering/.kitchen/kitchen-vagrant/ruby-win-windows-2012r2/windows-2012r2
---- End output of vagrant up --no-provision --provider virtualbox ----
Ran vagrant up --no-provision --provider virtualbox returned 1] on ruby-win-windows-2012r2
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

So I think it needs to be more specific in test kitchen which windows box to use

**Comment by rcjim** [comment]
Its a private image that I created some time back.  I was just adding that
to the README.

**Comment by isuftin** [comment]
@rcjim I can try one of the public images from Vagrant if it makes sense?

**Comment by rcjim** [comment]
Sure.  I need to start testing on Windows Server 2016, but I haven't had a
chance to build an image yet and if that works, then I could use them
instead.

Jim

**Comment by rcjim** [comment]
I don't remember for sure, but I think I might have used a datacenter
evaluation image.

**Comment by isuftin** [comment]
@rcjim I was able to test the Linux images, but the Windows image testing workflow is unclear. Not sure where to source the ISO so I will stop here. The Linux tests all validated. Looks good to me.

**Pull request merged**
